version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - DEFAULT_REGION=us-east-2
      - EDGE_PORT=4566
      - SERVICES=s3,lambda,logs,dynamodb
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-2
    ports:
      - '4566-4583:4566-4583'